### ISSUE TITLE
Activities view should be sorted in decending order

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#14]
The activities view seems to be ordered in chronological order with oldest first. The view would be much more helpful if it were ordered the other way around, with latest first.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/166db49c-3c25-4a20-a73b-8148c91b0639)

**Comment by Kumarapandian** [comment]
fixed in build UI_11.0.0.0.128
