### ISSUE TITLE
Manage runtimes view should show owner name

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#16]
The Manage runtimes view should show the owner name instead of a cryptic ID.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/b25df779-3d2b-480d-9f6c-71ec603755f7)

**Comment by thesse1** [comment]
Same for Manage Data Planes view:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/d6583bd9-f00a-44b3-8073-db6d5ec4ed03)

**Comment by Kumarapandian** [comment]
This issue has been fixed and will be available in the GA Release
