### ISSUE TITLE
Activities view for APIs should show runtime name

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#17]
The Activities view for APIs shows actions like Updated, Added, Versioned etc. This information is not very helpful without knowing on which runtime the action occurred.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/eaa0c27e-8d20-497e-b459-c3455adbdd73)

**Comment by Kumarapandian** [comment]
Has been taken care through https://itrac.eur.ad.sag/browse/WF-24863
