### ISSUE TITLE
Links in map do not work

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#18]
When I hover over an icon in the map, the cursor changes to become a link symbol (hand), but when I click the mouse button, nothing happens.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/c17a5e9a-ef90-4b6b-a6bc-7c117cadeb2a)

**Comment by Kumarapandian** [comment]
This will be available with the GA release
