### ISSUE TITLE
Icons lost after runtime restart

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#19]
I have defined icons (Azure logo) for all my runtimes in the Control Plane UI. Looks nice! But when I restart the API Gateways and they register again, the Control Plane forgets about the logos.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/b8eb0dfa-d07e-4551-af32-43a5c0376f21)

**Comment by Kumarapandian** [comment]
This issue has been fixed and is available along with the upcoming GA Release.
