### ISSUE TITLE
Action link on Manage data planes view does not work (yet)

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#21]
![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/befabe86-dc2b-455c-912a-b7d598be1b4f)

**Comment by thesse1** [comment]
Same for Manage APIs view:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/558eacd5-bda9-47aa-9956-aead5ca9a1c8)

**Comment by Kumarapandian** [comment]
We didn't have dataplane and API monitoring page for the beta release. It will be enabled in GA Release.
