### ISSUE TITLE
APIs, Runtimes and Data Planes should always be sorted in the same order

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#22]
APIs, Runtime and Data Planes come in varying orders in the Control Plane. It would be nicer if they would also be shown in the same order (easier to understand and use).

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/58db51e2-978a-4f85-b7de-1fd5a800aac4)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/22c14f4f-6992-4217-a26e-ce7817a19eaa)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/6e96865e-716d-4463-8ed4-e041c632d818)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/8a16a57d-3b9b-4a11-8b4f-3ad7843dab0c)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/cd7ff0db-3e75-4e8c-b321-4a9a08f62873)

**Comment by Kumarapandian** [comment]
This has been completed and tracked through https://itrac.eur.ad.sag/browse/WCO-2747
