### ISSUE TITLE
Manage APIs view should display API version

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#24]
You cannot tell versions apart:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/2214f81b-f2a7-4505-8cba-e7426dec35d3)

Only when you open the twister, the view will display the version number:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/1635fa7e-56e7-4e81-ae14-0b2ee8be8e6a)

**Comment by Kumarapandian** [comment]
Any API may have multiple versions and run on multiple runtimes, so we may not show the exact version number(s) in the header level. Hence the version information was shown in the expanded detailed view.
