### ISSUE TITLE
Persistent filter

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#25]
It would be very helpful if the user could save a set of filter criteria in their profile, or, at least, if the Control Plane could save it in the session. Currently, I am losing context every time I switch from one view to another. Thanks!

Best regards,
Thomas

**Comment by praveen-vaidyanathan** [comment]
@Kumarapandian  - We must do this improvement.  Let's track this closely

**Comment by Kumarapandian** [comment]
This will be taken care through the itrac https://itrac.eur.ad.sag/browse/WCO-2953
