### ISSUE TITLE
Status pop-up: Incorrect headings

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#27]
The headings of the status pop-up read: Name | Health | Current | Previous.

It should be: Name | Current | Time in current health | Previous - as in the corresponding dashboard pane.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/910ed25e-d6c0-43c4-a952-fa977695c62e)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/ee711019-361e-4ecd-a0d8-fe19cd9e0325)

**Comment by Kumarapandian** [comment]
This has been completed through https://itrac.eur.ad.sag/browse/WCO-2932
