### ISSUE TITLE
Status pane and pop-up: Entries should be sorted in ascending order

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#28]
It is more important for the user to see the most current changes first.

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/537681f9-5d5f-48de-b436-33d0a96d498b)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/869ac250-91b8-4c60-b6df-97f95aed1b6c)

**Comment by Kumarapandian** [comment]
This has been completed through itrac https://itrac.eur.ad.sag/browse/WCO-2933
