### ISSUE TITLE
Filter on dashboard

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#29]
The dashboard should also offer the option to filter the displayed objects. Otherwise, the map and the statistics panes are difficult to read and understand.

**Comment by vallabsag** [comment]
@thesse1  In the user-preferences, you can already hide the widgets even for dashboard page if you feel some of the widgets are not necessary for that particular user login. 

Filter option is not added in this page as per the design but you can use the filter/hide option from the user preferences to hide/filter out the widgets from this page. 

If you still think the filter option at the page level is still needed, please raise a brainstorm request. 

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/131241872/25ebe59c-6fd2-4be2-843f-aac92e1099ce)
