### ISSUE TITLE
Missing filter on Manage runtimes page

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#33]
On Manage data planes and on Manage APIs, you can filter by status, but not on Manage runtimes:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/110e2be3-c984-462a-a4e6-f3a062530528)

**Comment by Kumarapandian** [comment]
This will be tracked as feature in https://itrac.eur.ad.sag/browse/WCO-3007
