### ISSUE TITLE
Error running docker-compose -f control-plane-beta.yaml up -d

### ISSUE THREAD

**Issue by kalpshekhar-sag** [SoftwareAG/webmethods-api-control-plane#34]
After successful login, I get the following error while running  docker-compose -f control-plane-beta.yaml up -d

Pulling ingress (ghcr.io/softwareag/webmethods-api-control-plane/ingress:latest)...
ERROR: denied

**Comment by Kumarapandian** [comment]
The issue was with the access permission for the PAT used to the github packages.

After providing the proper access, and updating the docker-compose setup in the VM, the application started properly.
