### ISSUE TITLE
Documentation --- Location and Region

### ISSUE THREAD

**Issue by enowaksag** [SoftwareAG/webmethods-api-control-plane#48]
In the documentation, list all the valid options for:
* Location
* Region

Setting 
* Location=Oregon
* Region=us-east-1
Puts the pin around Chicago.

Setting
* Location=Virginia
* Region=us-east-1
Puts the pin in Brazil -- Rio De Janeiro

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/84510695/f12511e5-da2d-49c1-99bd-d4f2857206d9)

Why not do an IP Address lookup to determine what the actual location is?  And have an override if necessary.

**Comment by Kumarapandian** [comment]
We will work on this and update you.

**Comment by Kumarapandian** [comment]
This will be addressed as part of the feature https://itrac.eur.ad.sag/browse/WF-29241.
